import { FileText } from 'lucide-react';
import { useApp } from '@/app/context/AppContext';

export const Summary = () => {
  const { currentVideo } = useApp();

  if (!currentVideo) return null;

  const paragraphs = currentVideo.summary.split('\n\n');

  return (
    <div className="bg-white/80 dark:bg-neutral-900/80 backdrop-blur-sm rounded-2xl shadow-lg border border-neutral-200 dark:border-neutral-800 p-8">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-indigo-100 dark:bg-indigo-950 flex items-center justify-center">
          <FileText className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
        </div>
        <h2 className="text-2xl font-semibold text-neutral-900 dark:text-white">
          AI-Generated Summary
        </h2>
      </div>

      <div className="prose prose-neutral dark:prose-invert max-w-none">
        {paragraphs.map((paragraph, index) => (
          <p 
            key={index}
            className="text-neutral-700 dark:text-neutral-300 leading-relaxed mb-4 last:mb-0"
          >
            {paragraph}
          </p>
        ))}
      </div>

      <div className="mt-6 pt-6 border-t border-neutral-200 dark:border-neutral-800">
        <p className="text-sm text-neutral-500 dark:text-neutral-400 italic">
          This summary was automatically generated by AI and provides a comprehensive overview of the video content.
        </p>
      </div>
    </div>
  );
};
